// This file is generated by Astro DB
declare module 'astro:db' {
	export const Guestbook: import("@astrojs/db/runtime").Table<
		"Guestbook",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Guestbook","primaryKey":true}},"content":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"content","collection":"Guestbook","primaryKey":false,"optional":false}},"author":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"author","collection":"Guestbook","primaryKey":false,"optional":false}},"url":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"url","collection":"Guestbook","primaryKey":false,"optional":true}},"timestamp":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"timestamp","collection":"Guestbook","default":{"__serializedSQL":true,"sql":"CURRENT_TIMESTAMP"}}},"theme":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"theme","collection":"Guestbook","primaryKey":false,"optional":false}},"isSpam":{"type":"boolean","schema":{"optional":true,"unique":false,"deprecated":false,"name":"isSpam","collection":"Guestbook"}}}
	>;
}
