
import __ASTRO_IMAGE_IMPORT_g6bBx from "./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnow%2Fbooks%2F001.yml";
import __ASTRO_IMAGE_IMPORT_2urboQ from "./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnow%2Fmovies%2F001.yml";
import __ASTRO_IMAGE_IMPORT_Z2c9O6v from "./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnow%2Fmusic%2F001.yml";
import __ASTRO_IMAGE_IMPORT_ealcM from "./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout%2Fabout.en.md";
import __ASTRO_IMAGE_IMPORT_6EVY7 from "./img1200.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fabout%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_qm08e from "./img600.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fcolophon%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zm77TO from "./img900.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fcolophon%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2vFwSt from "./img1200.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fcolophon%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1NQ3hy from "./showcase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2018%2Fdropbox%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2f69Vv from "./commons-timeline.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2019%2Fcityblock%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZieYXR from "./commonplace.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2019%2Fcityblock%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zm5RhL from "./namesake-cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2024%2Fnamesake%2Findex.md";
export default new Map([["./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnow%2Fbooks%2F001.yml", __ASTRO_IMAGE_IMPORT_g6bBx], ["./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnow%2Fmovies%2F001.yml", __ASTRO_IMAGE_IMPORT_2urboQ], ["./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fnow%2Fmusic%2F001.yml", __ASTRO_IMAGE_IMPORT_Z2c9O6v], ["./1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fabout%2Fabout.en.md", __ASTRO_IMAGE_IMPORT_ealcM], ["./img1200.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fabout%2Findex.mdx", __ASTRO_IMAGE_IMPORT_6EVY7], ["./img600.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fcolophon%2Findex.md", __ASTRO_IMAGE_IMPORT_qm08e], ["./img900.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fcolophon%2Findex.md", __ASTRO_IMAGE_IMPORT_Zm77TO], ["./img1200.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpages%2Fcolophon%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2vFwSt], ["./showcase.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2018%2Fdropbox%2Findex.md", __ASTRO_IMAGE_IMPORT_1NQ3hy], ["./commons-timeline.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2019%2Fcityblock%2Findex.md", __ASTRO_IMAGE_IMPORT_2f69Vv], ["./commonplace.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2019%2Fcityblock%2Findex.md", __ASTRO_IMAGE_IMPORT_ZieYXR], ["./namesake-cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwork%2F2024%2Fnamesake%2Findex.md", __ASTRO_IMAGE_IMPORT_Zm5RhL]]);
		